### ISSUE TITLE
Display useful information after running litd

### ISSUE THREAD

**Issue by justinpobrien** [lightninglabs/lightning-terminal#120]
We should provide users with more useful information after starting `litd` for the first time.

- Node status
- Network (regtest, testnet, mainnet)
- Node alias
- LND version
- Web interface URL

![carbon (14)](https://user-images.githubusercontent.com/10817083/94240115-7f327800-feae-11ea-8fed-8a61d3fe0870.png)

**Comment by justinpobrien** [comment]
Add a distinct configuration flag that will display the logs in the command line. But by default it's false.

`--log-to-stdout=True`

**Comment by guggero** [comment]
Unfortunately, turning off logging to the console/standard output currently isn't possible without completely turning off logging in general (would mean also no logs in the log file). This can easily be fixed with a change in `lnd` but for LiT v0.2.0 I think we don't want to wait for another minor version to come out.

Therefore I'd suggest that we create a separate issue for "not logging to console by default" that we can tackle in a later sprint.
