### ISSUE TITLE
No option to close account?

### ISSUE THREAD

**Issue by andywang514** [lightninglabs/lightning-terminal#197]
Under lightning pool, I have funded my account but don't see an option to close it. 

I'm using the LT app from umbrel node set up. 

I also get "unable to fetch the last batch" error from time to time in the interface.

**Comment by jamaljsr** [comment]
> Under lightning pool, I have funded my account but don't see an option to close it.

This was fixed in https://github.com/lightninglabs/lightning-terminal/pull/191 and released in [v0.4.1-alpha](https://github.com/lightninglabs/lightning-terminal/releases/tag/v0.4.1-alpha). You'll need to wait a bit for Umbrel to update the version of Terminal they use.

> I also get "unable to fetch the last batch" error from time to time in the interface.

This is likely a connectivity issue between your computer/browser and the Umbrel node. I'm not sure if there's much we can do on our end other than not showing an error popup in this case. The website attempts to fetch new data every minute, so it will attempt it again. You can always just reload the page to ensure you are looking at accurate data.
