### ISSUE TITLE
Loop Out Request Stuck In Initiated State

### ISSUE THREAD

**Issue by kvanderhoek** [lightninglabs/lightning-terminal#239]
Over 3 day ago I initiated a Loop Out request for 3.7m stats from my node Sparky75 through my channel to CoinGate.  It’s been over 14 hours and the Loop Out request is still stuck in the Initiated phase.  The ID associated with this Loop Out is C04AE34C5005056A36D6CC024A6C8EFD7B213B91F24ACDD9706C0E30B4274DCA (Lightning Terminal screen capture of the Loop Out attached)

Of additional concern is that my channel with CoinGate is in a bad state and it got into this bad state after performing the Loop Out.  It’s a 5m sat channel but according all my dashboards it only has 54,046 sats of inbound liquidity and 3,092,264 sats of outbound liquidity.  The sum total of this liquidity is 1.85m sats less than the 5m sat channel size (screen capture from Lightning Terminal of bad channel state attached).  I started seeing the channel balance fluctuate dramatically after I initiated the Loop Out and it eventually settled on the above numbers.  Note I did quickly restart my node after initiating the Loop Out request.  It only took about 4 minutes.  I’m not sure if that contributed to the issue.

According to Ryan Gentry from Lightning Labs the LoopOut transactions failed on your end yet the Lightening Terminal UI on my end still says it's in progress.

Does Lightning Labs engineering team have any thoughts on what might have caused the Loop Out to fail? Any thoughts on where the 1.85m sats from my channel may have ended up?

**Comment by carlaKC** [comment]
> The ID associated with this Loop Out is C04AE34C5005056A36D6CC024A6C8EFD7B213B91F24ACDD9706C0E30B4274DCA

This loop out has been cancelled back by the server, so the payment should eventually fail back. We have recently addressed a bug in lnd where failed payments get stuck, this should be addressed by upgrading to lnd 0.13. 

>  It’s a 5m sat channel but according all my dashboards it only has 54,046 sats of inbound liquidity and 3,092,264 sats of outbound liquidity.

Your channel may have other payments that are in flight, which could explain the difference between channel capacity and inbound/outbound. You can check out `lncli listchannels` to see what's still pending on your channel. Based on the amount, this sounds unrelated to loop.

> screen capture from Lightning Terminal of bad channel state attached

Could you upload this again? It doesn't seem to have come through.

>  Note I did quickly restart my node after initiating the Loop Out request

This should not affect loop out at all, so no worries here.

> Does Lightning Labs engineering team have any thoughts on what might have caused the Loop Out to fail?

Your loop out failed because your swap payment could not reach the loop server. I would suggest trying a smaller swap size, or improving your node's liquidity using some of the recommendations listed on: https://terminal.lightning.engineering when you lookup your node pubkey.

**Comment by kvanderhoek** [comment]
Thanks for the comments Carla. Checking Lightning Terminal this morning I see that the loop out finally shows as failed on my end.  Even better, my channel balance seems to be correct and the missing 1.85m sats are back in the channel with the channel now showing the full 5M sats.  Possible it just took a while for things to correct themselves.

Here is the image of the channel in the bad state that I forgot to attach to the ticket.  Again this has now been corrected.

<img width="1124" alt="Screen Shot 2021-06-20 at 1 00 59 PM" src="https://user-images.githubusercontent.com/4307769/123465949-991afb80-d5a3-11eb-9948-12276345c95d.png">

**Comment by jamaljsr** [comment]
Thanks for the update. Happy to see the issue resolved. I'll close this issue now.
