### ISSUE TITLE
loop out stuck in "initiated"

### ISSUE THREAD

**Issue by jcbelair** [lightninglabs/lightning-terminal#303]
Hello, I started a loop out from my channel to send some sats onchain and its stuck.. 

Thats what i See in LIT
Can anyone help me?

I just went straight with the defaults.. No channels picked.. 
Thanks.

![IMAGE 2021-12-27 14:29:40](https://user-images.githubusercontent.com/56407691/147505253-46307327-78a2-4683-a215-cccb84102f40.jpg)

**Comment by jcbelair** [comment]
update.. it failed....

**Comment by jamaljsr** [comment]
This appears to have been caused by the miner fee being set too low in the code (not something you can control). We should set the `MaxMinerFee` value to the same value used by the CLI (https://github.com/lightninglabs/loop/blob/5f0c1180882aa761a0b2f463247b05a4965fc93e/cmd/loop/main.go#L263). 

Going to keep this issue open until the value is updated.

**Comment by jcbelair** [comment]
thanks.. for the loops that are stuck.. shall I just wait?
one has been there for more than 24hrs..  (16M sats) 
![Screen Shot 2021-12-28 at 20 24 00](https://user-images.githubusercontent.com/56407691/147621444-cd4b68b3-8f9e-4fd7-9603-68d897e37a34.png)
