### ISSUE TITLE
Lightning Terminal - Unable to fetch sessions error

### ISSUE THREAD

**Issue by theDavidCoen** [lightninglabs/lightning-terminal#326]
Just installed Lightning Terminal and set 
```
export LIT_PASSWD="MySeCretPassWoRd"
. ./btcpay-setup.sh -i
```
of course I changed the password above with a valid one.

However, since the very first login, I get the error:
```
Unable to fetch sessions: 
/rpc.Sessions/ListSessions: unknown permissions required for method
```

Image attached.
![Immagine 2022-01-13 125857](https://user-images.githubusercontent.com/38695835/149340620-4ffbe727-7895-41b6-96fa-26293430e770.png)

I have this warning at the login and if I try to copy pairing phrase or create a new session.

I'm running BTCPay Server v1.4.4.0 but I'm not sure of the current version of Lightning Terminal.

Any idea?

**Comment by guggero** [comment]
Thanks for the report. I suspect this needs a fix in BTCPayServer. See https://github.com/lightninglabs/lightning-terminal/pull/306. The BTCPayServer nginx redirects the session calls to lnd instead of LiT.
The changes that #306 did in the example need to be applied to: https://github.com/btcpayserver/btcpayserver-docker/blob/master/Production/nginx.tmpl#L147

To verify this is the actual problem: Could you please check if you see the `unknown permissions required for method` in the `lnd` log instead of the LiT log?

**Comment by theDavidCoen** [comment]
@guggero I have a very long log in lnd so I cannot find `unknown permissions required for method`

**Comment by guggero** [comment]
Can't you just trigger the error again by opening LiT and then do `docker logs <lnd-container-name> | grep "unknown permissions"`?

**Comment by theDavidCoen** [comment]
@guggero an update https://github.com/btcpayserver/btcpayserver-docker/pull/602

**Comment by guggero** [comment]
Closing this as should be fixed by https://github.com/btcpayserver/btcpayserver-docker/pull/602.
