### ISSUE TITLE
Lightning Terminal - wrong link for Lightning Node Connect 

### ISSUE THREAD

**Issue by theDavidCoen** [lightninglabs/lightning-terminal#327]
On BTCpay server version 4.4.0, If you open Lightning Terminal and click on Lightning Node Connect, you get https://YOURBTCPAYSERVER/connect instead of https://YOURBTCPAYSERVER/lit/connect.

Not sure it's a general bug or just for the Lightning Terminal version on BTCpay server version 4.4.0.

**Comment by guggero** [comment]
Thanks for the report. It looks like BTCPayServer is using LiT `v0.6.1-alpha`: https://github.com/btcpayserver/btcpayserver-docker/blob/master/docker-compose-generator/docker-fragments/opt-add-lightning-terminal.yml#L7
The problem you mentioned was fixed in https://github.com/lightninglabs/lightning-terminal/pull/301 which was released in `v0.6.2-alpha`.

So to fix this, the version in BTCPayServer needs to be bumped.
