### ISSUE TITLE
Umbrel Update leads to new Lightning Pool Account

### ISSUE THREAD

**Issue by snarflakes** [lightninglabs/lightning-terminal#346]
Did the most recent umbrel update and had to re-install Lightning Terminal because i was locked out due to password being automatically changed. When I went to my lightning pool, it doesn't show the old account (the lockdown period ended along time ago), it says Welcome to Pool and no logging of my old Lightning Pool account info, so i guess I need to proceed with account recovery.  

BUUUT, Would any funds even be left over if the lockdown period ended already, it auto-closes the pool account right?

Also it would good to know if I am selling channels, they won't auto-close in the pre-negotiated time frame. I will have to manually close them when the channel rental time expires. But how am I supposed to know when the rental time has expired a channel once it has been created, should there be an alert?

Also there is no units on the channel duration field in the bid/ask additional options drop down.

thanks,
Snarflakes

**Comment by guggero** [comment]
No, the account won't auto-close since a signature from your node is required.
You can recover the account (see https://docs.lightning.engineering/lightning-network-tools/lightning-terminal/troubleshooting#pool-account-recovery) and then close it or continue to use it.

There's a [thaw height](https://docs.lightning.engineering/lightning-network-tools/pool/channel_leases#service-level-lifetime-enforcement) that you can look at in `lncli listchannels`. That will tell you when the lease time is over and you're allowed to close the channel.

> Also there is no units on the channel duration field in the bid/ask additional options drop down.

It's always in blocks (ans the latest version also shows the time in weeks/months).

Closing the issue as everything is working as expected and as documented.

**Comment by snarflakes** [comment]
thanks for all the clarification! love the lightning pool account capabilities.
