### ISSUE TITLE
Channel sold in pool, pending for over a week.

### ISSUE THREAD

**Issue by iksolon** [lightninglabs/lightning-terminal#443]
Hey guys!

I sold a channel in the pool more than a week ago and that channel is pending to open until now.

In the meantime I opened other channels on my own that opened normally, but this one from the pool is still pending to open.

Can you help me?

hash a2807486889f83c724124266a3393cd00e088a5d70d167f01d40c68428aef8a0
Transaction not found.

<img width="637" alt="Screenshot 2022-10-29 at 09 49 27" src="https://user-images.githubusercontent.com/107311059/198832515-37d1342c-f8dd-4f5c-8da2-650450b64c97.png">

I am using umbrel 0.5.2 on a raspberry pi 4 8gb. Lightning Terminal 0.8.2-alpha.
All the apps and OS are all updated to the latest version available on the umbrel.

**Comment by levmi** [comment]
Hi! Happy to help. First, I'll just gather some information to help the team better debug your issue. Do you know the pubkey of the peer the channel was being opened to? Also, do you have your trader key from Pool? Finally, do you have any logs from litd during the time period that the channel was opened? All can be helpful with debugging in various ways.

**Comment by positiveblue** [comment]
It looks like the `a2807486889f83c724124266a3393cd00e088a5d70d167f01d40c68428aef8a0` tx was a batch attempt that never went trough (because of your node or others not accepting the batch). It would be really useful to check the logs for terminal and LND during the time that this happen Oct 21, 2022 19:02:55 - 19:03:20 UTC.

I have some questions about your client:
- Is the pool daemon up?
- What is your trader key?
- What is the status of your account?
- What is the status of your orders?
- Did you participate in any other matches after this one?

**Comment by iksolon** [comment]
Thaks very much!

Pubkey of the peer User21952
0236e577964da670c730e7f362fa0c561b75dc9af02c0d822179f155e1455b20bd

Tader key
038444b4bcccec17443a4d73c01b39ce2183d9407cbbb3e6058465a056cf69083c

<img width="780" alt="Screenshot 2022-10-29 at 17 33 37" src="https://user-images.githubusercontent.com/107311059/198851392-47f5efd7-ad2b-496e-b987-2014e85c4b93.png">


<img width="664" alt="Screenshot 2022-10-29 at 17 34 38" src="https://user-images.githubusercontent.com/107311059/198851414-6477d0af-e1e8-4a39-8f92-6f45a5c5dc92.png">

**Comment by positiveblue** [comment]
There was an intend to sell a channel in one batch but it did not go through. It looks like your lnd node was not able to clean the state of that failed try. I would advice to check the logs of your terminal daemon/lnd node during that time to see why it was not  cleaned up.

Your account is now expired (or close to expire) but this order could have match without any problem during the last week (it did not, so double check that terminal was connected to the auctioneer) but you should be able to interact with your account without any issue: deposit/withdraw funds, submit orders, etc..

Feel free to cancel that channel open from LND manually.

**Comment by iksolon** [comment]
Got it.

But how do I cancel a channel that is opening? 

In LNDg I need to enter the ID to perform the cancellation of a channel. But since it is opening, there is no ID yet.

**Comment by positiveblue** [comment]
I guess there is no other way than using the `abandonchannel` lncli subcommand @guggero? Does chantools have a safer way to do this?

**Comment by guggero** [comment]
@iksolon that pending channel should've been cleaned up by Pool/Lit automatically. Did you stop LiT for some reason?

But yes, in this case, because it's verifiable that the funding transaction will never confirm (since it was a Pool batch transaction that was never finalized), you can use the `lncli abandonchannel a2807486889f83c724124266a3393cd00e088a5d70d167f01d40c68428aef8a0 0 --i_know_what_i_am_doing` command (which is what Pool would've used internally too to clean up a batch that didn't go through).

**Comment by iksolon** [comment]
I don't know about LiT, but I experienced a bug a few days ago (reported in #437), where my pool account showed up as closed and I had to recover it by following your directions. This could be it.

Anyway, problem solved. Thanks again for your attention!

![photo_2022-10-31 07 28 38](https://user-images.githubusercontent.com/107311059/198987532-45e5f7e3-2f22-436b-a0ff-01d5a1051eab.jpeg)

**Comment by iksolon** [comment]
last question: is it ok if I leave my trader key published here?

**Comment by guggero** [comment]
Ah, okay. So the recovery explains why the channel wasn't cleaned up automatically, Pool didn't have the required information to do it. But happy to hear that the command helped solve the problem.

The trader key is not particularly sensitive, I would say it's okay to keep it here (AFAIK updating the comments will only hide it in the last version of the comment while the previous versions can still be looked at, so things aren't deleted by GitHub really).

Closing the issue as everything seems either explainable or solved.
