### ISSUE TITLE
Lost access to funds after reinstallation of LiT while account was still pending after first deposit.

### ISSUE THREAD

**Issue by abv4594** [lightninglabs/lightning-terminal#470]
Hi all,
Pls find below the steps which took me to the problem.

0) Environment: Umbrel + RaspberryPi
1) I was trying to use the Terminal / Pool for the first time after becoming T1.
2) I was trying to open an account but facing an error (something related to macaroon).
3) Before asking for help, I updated all Apps (including Bitcoin Node, Lightning Node, ...).
4) After I updated, I could successfully open the account. Which appeared with the status "pending".
5) After a few blocks (I believe more than 6) it was still "pending". Meanwhile, I got another error in Terminal.
6) I had the "brilliant" (wrong) idea of removing and reinstalling the Terminal.
7) Then when I enter Terminal > pool I don't see the account/funds anymore. Account recovery also not working.
8) Contacted the team via Slack. Based on the TxID of the first deposit, @guggero identified that the account on the server side to which the funds were deposited didn't match the account my terminal is trying to connect, which doesn't exist on the server side. 
9) Following his suggestion, I reinstalled LiT again, and without entering the UI, run the account recovery once more. But it also didn't work. 
Pls advise if it's safe to attach here logs and TxID.

**Comment by colonel34** [comment]
Same thing happened to me, any solution?

**Comment by abv4594** [comment]
Nothing new yet on my end. I will try again the slack channel.

**Comment by guggero** [comment]
@colonel34 did you try the [account recovery](https://docs.lightning.engineering/lightning-network-tools/lightning-terminal/troubleshooting#pool-account-recovery)?

**Comment by guggero** [comment]
Thanks @abv4594 for the assistance in figuring out what the problem was.

The reason the account recovery didn't work was because the account's derivation index (28) was larger than the number of keys we try during a recovery by default (20).
To detect this, we simply had to run `lncli wallet accounts list | grep -A3 /220` to see that the `external_key_count` was at 29.
Then simply running `pool accounts recover --account_target 30` did bring back the account into normal operation.
