### ISSUE TITLE
RBF channel open visually stuck at "Pending Confirmations" in Channel Actions

### ISSUE THREAD

**Issue by eliotcougar** [lightninglabs/lightning-terminal#511]
I opened a channel, and later had to bump the fee using the RBF mechanism... The channel has been opened successfully, but on https://terminal.lightning.engineering it still says that it's Pending Confirmations because it's probably waiting for the original 1sat/vB tx id to confirm…

**Expected behavior**

It should keep track of RBF transactions somehow…

**Actual behavior**

The channel opening operation is still displayed on https://terminal.lightning.engineering in Channel Actions as "Pending confirmations"

**To reproduce**

Open a channel with low fee
Bump the fee in LND
Wait for the RBF transaction to confirm

**System information**

litd 0.8.5 and 0.8.6, lnd-remote with lnd 0.15.5 on Windows x64

**Comment by guggero** [comment]
You _CANNOT_ use RBF to replace a funding transaction! You have to use CPFP, otherwise you risk losing funds. An RBF transaction has a different TXID so the commitment transaction that was negotiated with the remote peer is invalid.

So what exactly did you do? Because if you used the `lncli bumpfee` command, that would've created a CPFP transaction which is okay. If you did use another mechanism, you might need to recover this channel manually with the help/cooperation of your peer.

**Comment by eliotcougar** [comment]
Ah, yes it used CPFP... Though, the original tx has been in mempool limbo for about 5-6 days before I bumped the fee...
In any case, I'm sorry for opening the bug report so quickly - it turns out to be a caching issue... After clearing the local data, logging back in, and repopulating the data (it took a while), it now shows the correct date of confirmation...
