### ISSUE TITLE
pending update

### ISSUE THREAD

**Issue by patripb** [lightninglabs/lightning-terminal#523]
Hi! 
My pool account has been stuck for a week "pending update" after I tried to add funds. The tx was never made into the mempool and I think it was rejected because the low fees (2sat/vb).

tx: bd9a9b1cbb4f49d9840b7c276043c52ab45bb73edfd1cdd2fb1348bb32f382b2

trader key: 03508b7888ba08c43134bd1d97c94dd95a8d0148e3fd4a1d93dc268dc66e8bc4ed

as suggested, i tried to bumpfee and got this error: 
[pool] rpc error: code = Unknown desc = transaction bd9a9b1cbb4f49d9840b7c276043c52ab45bb73edfd1cdd2fb1348bb32f382b2 did not contain any eligible outputs to CPFP

I also increased to 1Gb the mempool size memory, restarted my node and tried the bumpfee again, but got the same error.

**Comment by guggero** [comment]
I checked on the server side and the problem is that one of the inputs that was used for the account update has already been spent in the meantime. Probably because the TX never made it into the mempool, lnd didn't see it as being used elsewhere.

I removed the account diff on the server side. You'll now need to run `pool accounts recover` to sync the account state. If that doesn't work and the account goes back to `STATE_OPEN`, you'll need to delete the `pool.db` file first, then run the account recovery.

Please note that the account recovery will cancel any open orders, but you'll be able to re-create them once the account is back in working condition.

**Comment by patripb** [comment]
Done! Thanks a lot.

**Comment by patripb** [comment]
Yes, solved. Recover my pool account and got back my funds.
