### ISSUE TITLE
Lightning terminal status error - invalid password

### ISSUE THREAD

**Issue by rapidsequence** [lightninglabs/lightning-terminal#557]
Not sure if this is the right place to ask for help, but my lightning terminal on my MyNode is giving me this error below:

May 18 15:31:25 myNode systemd[1]: lit.service: Failed with result 'exit-code'.
May 18 15:31:25 myNode systemd[1]: lit.service: Main process exited, code=exited, status=1/FAILURE
May 18 15:31:25 myNode lit[10949]: error starting macaroon service: unable to unlock macaroon DB: invalid password
May 18 15:31:25 myNode lit[10949]: 2023-05-18 15:31:25.142 [DBG] GRPC: [core] Subchannel Connectivity change to SHUTDOWN
May 18 15:31:25 myNode lit[10949]: 2023-05-18 15:31:25.142 [DBG] GRPC: [core] Channel Connectivity change to SHUTDOWN
May 18 15:31:25 myNode lit[10949]: 2023-05-18 15:31:25.142 [DBG] GRPC: [core] Subchannel Connectivity change to SHUTDOWN
May 18 15:31:25 myNode lit[10949]: 2023-05-18 15:31:25.142 [DBG] GRPC: [core] Channel Connectivity change to SHUTDOWN
May 18 15:31:25 myNode lit[10949]: 2023-05-18 15:31:25.142 [DBG] GRPC: [core] Subchannel Connectivity change to SHUTDOWN
May 18 15:31:25 myNode lit[10949]: 2023-05-18 15:31:25.142 [DBG] GRPC: [core] Channel Connectivity change to SHUTDOWN
May 18 15:31:25 myNode lit[10949]: 2023-05-18 15:31:25.142 [DBG] LNDC: Lnd services finished
May 18 15:31:25 myNode lit[10949]: 2023-05-18 15:31:25.142 [DBG] LNDC: Wait for router to finish
May 18 15:31:25 myNode lit[10949]: 2023-05-18 15:31:25.142 [DBG] LNDC: Wait for invoices to finish
May 18 15:31:25 myNode lit[10949]: 2023-05-18 15:31:25.142 [DBG] LNDC: Wait for chain notifier to finish
May 18 15:31:25 myNode lit[10949]: 2023-05-18 15:31:25.142 [DBG] LNDC: Wait for client to finish
May 18 15:31:25 myNode lit[10949]: 2023-05-18 15:31:25.142 [DBG] GRPC: [core] Subchannel Connectivity change to SHUTDOWN
May 18 15:31:25 myNode lit[10949]: 2023-05-18 15:31:25.141 [DBG] GRPC: [core] Channel Connectivity change to SHUTDOWN
May 18 15:31:25 myNode lit[10949]: 2023-05-18 15:31:25.141 [DBG] LNDC: Closing lnd connection
May 18 15:31:25 myNode lit[10949]: 2023-05-18 15:31:25.141 [ERR] LITD: Could not start subservers: error starting macaroon service: unable to unlock macaroon DB: invalid password
May 18 15:31:24 myNode lit[10949]: 2023-05-18 15:31:24.616 [INF] LNDC: Macaroon DB could not be unlocked with the derived shared key. Attempting to unlock with empty password instead
May 18 15:31:24 myNode lit[10949]: 2023-05-18 15:31:24.315 [INF] LITD: Starting integrated faraday daemon
May 18 15:31:24 myNode lit[10949]: 2023-05-18 15:31:24.314 [INF] LNDC: lnd is now fully synced to its chain backend

I have not changed the original password. I have tried reinstalling the app on my MyNode and also resetting it with no success. Has anyone seen this error before or know what to do? I am not a programmer so this is very foreign to me. Thank you.

**Comment by ellemouton** [comment]
Hi @rapidsequence  - this could happen if you are possibly have a Litd folder lying around from a previous installation with a different LND node. Have you had a previous LND node before?

**Comment by sarmahsubham-mp** [comment]
Hi @ellemouton I am facing the same issue, I do not have litd folder lying around although I have previously installed a different version of lnd (0.17.5) then deleted all the files and moved to 0.17.0 for litd compatibility.

**Comment by ViktorTigerstrom** [comment]
Hi @sarmahsubham-mp! Which version of `litd` are you running? Could you please run the `litcli status` command and post the output of that command here? Hopefully that'll detail the underlaying issue for you.

Also, just as a side note since you mentioned that you've downgraded to `lnd` v0.17.0 for `litd` compatibility:
The latest litd version is compatible with the later `lnd` than `v0.17.0-beta` when running `lnd` in `remote` mode, so there's no need to downgrade `lnd`.
We've realised that the the "compatibility" section in the README is very unclear regarding this, but the first table that shows the "minimum" `lnd` version you can use with the respective `litd` version, when `lnd` is running in `remote` mode. We'll be updating the wording regarding this soon to make that clearer.

**Comment by sarmahsubham-mp** [comment]
I am running the latest version of litd with lnd 17.0.

I have figured out the issue and fixed it. I tried to install litd a year ago and while uninstalling I did not delete the .pool, .loop and .faraday folders in ~. I did a clean reinstall of litd again after deleting these folders and this issue was fixed. Thanks a lot for helping.

**Comment by ellemouton** [comment]
great to hear @sarmahsubham-mp !

Im gonna close the issue now - @rapidsequence, feel free to re-open if you still encounter this issue 🙏
