### ISSUE TITLE
Ability to add custom LNC mailbox server to GUI

### ISSUE THREAD

**Issue by secondl1ght** [lightninglabs/lightning-terminal#601]
As mentioned in the LND devloper Slack:

I see in the docs here https://docs.lightning.engineering/lightning-network-tools/aperture/mailbox#docs-internal-guid-6d497483-7fff-ccdd-3290-061a74b72572 that once you setup your own LNC Mailbox with Aperture you then need to run a CLI command with litd `litcli sessions add --label="My own mailbox" --type admin --mailboxserveraddr lnc.yourlightningapp:443` before you can use your own Mailbox to connect to applications. I think it would be good if the above command was exposed in the GUI of Terminal so that non-technical users can add custom Mailboxes. This would make it easier for more Mailbox providers to popup. For example if an LNC app has its own Mailbox, users can access it more easily than having to use the CLI which is a non-starter for a lot of people.

**Comment by AndySchroder** [comment]
My issues seem related:

- https://github.com/lightninglabs/lightning-terminal/issues/586
- https://github.com/lightninglabs/lightning-terminal/issues/588

**Comment by secondl1ght** [comment]
I found this in the GUI under Custom Permissions > Advanced Options when creating a new LNC connection. So it looks like this functionality is already possible? Although it is fairly hidden.

![image](https://github.com/lightninglabs/lightning-terminal/assets/85003930/24e30312-3610-49d8-8519-50c79b18ac91)

**Comment by guggero** [comment]
Yes, that feature is already present. There's always a tradeoff between a simple to use UI for everyone and having all the options for power users. So if you have an idea of how to make this more apparent to power users without confusing most other users, we're all ears. I personally always open all "advanced options" sections in all UIs since I know that's where the good stuff usually is hidden.

Closing the issue for now, feel free to re-open if you think this needs adjustment.
