### ISSUE TITLE
Unable to perform loop-out

### ISSUE THREAD

**Issue by Redinpais** [lightninglabs/lightning-terminal#610]
![Captura de ecrã 2023-07-30 115213](https://github.com/lightninglabs/lightning-terminal/assets/17316352/6e004d84-d50d-414a-8352-0541f7c2d484)
Greetings.
After triying do a loopout, it give that error
What could be do?
Thanks?

**Comment by guggero** [comment]
There is a one-time payment of 1 satoshi your node needs to be able to pay before it can access the Loop service. That payment seems to have failed and you need to try again. What software platform are you using? Umbrel, MyNode, self-built?

**Comment by Redinpais** [comment]
I had no idea about that requirement.
I am with Umbrel. Do you have a procedure on how to do it?
Thank you.

**Comment by guggero** [comment]
See https://docs.lightning.engineering/lightning-network-tools/lightning-terminal/loop-fees.

I'm not an Umbrel user, so I hope this works. Might need some trial and error. Or you might need to get support from the Umbrel team if a command doesn't work:
 - Log into the Umbrel terminal
 - Find the docker process (lightning-terminal) with `docker ps`, copy the container ID that looks something like `340a5b0839f1`
 - Open the lightning-terminal container with `docker exec -it <container_id_from_previous_command> /bin/bash`
 - Find out where the pending token is located: `pool --tlscertpath "/data/.lit/tls.cert" --rpcserver localhost:8443 --macaroonpath /data/.loop/mainnet/loop.macaroon listauth`, look for the value of `file_name`, should be something like `/data/.loop/mainnet/lsat.token.pending`
 - Delete the pending token: `rm <full_path_from_above_file_name`, so for example `rm /data/.loop/mainnet/lsat.token.pending`
 - Try again

Though remember, this will only work if you have active channels and are able to pay the 1 satoshi for the token.

Closing the issue since it's not a problem with lightning-terminal. Feel free to continue the thread if things don't work out.
