### ISSUE TITLE
Status started but not finished

### ISSUE THREAD

**Issue by Redinpais** [lightninglabs/lightning-terminal#636]
Greetings.
I'm trying to do a loopout but I'm afraid I'm not succeeding because of an unexpired move.
How do I get it to finish?
![Captura de ecrã 2023-08-30 144644](https://github.com/lightninglabs/lightning-terminal/assets/17316352/3503d05a-fd02-4912-ab20-ada5bdbd3b01)
Thanks

**Comment by levmi** [comment]
Hi, thanks for the report. How many channels do you have open with how much inbound and outbound liquidity? To Loop Out, you need a payment of that size to reach Loop. If you don't have quality and enough outbound, then it would result in an off-chain failure.

**Comment by Redinpais** [comment]
I have 24 channels each of 10MM and some full assets.
But my biggest concern is to get rid of the move I made on August 28th that won't end and may be bringing complications to the process.How should I finish this registration so that it doesn't constantly stay in "Initiated"?
Regards.
António Pais




 

    Em quarta-feira, 30 de agosto de 2023 às 15:26:46 WEST, ***@***.***> escreveu:  
 
 


Hi, thanks for the report. How many channels do you have open with how much inbound and outbound liquidity? To Loop Out, you need a payment of that size to reach Loop. If you don't have quality and enough outbound, then it would result in an off-chain failure.

**Comment by Redinpais** [comment]
After almost two days, it was finally unlocked.We can close the ticket. Thank you very much.
António Pais


    Em quarta-feira, 30 de agosto de 2023 às 15:26:46 WEST, ***@***.***> escreveu:  
 
 


Hi, thanks for the report. How many channels do you have open with how much inbound and outbound liquidity? To Loop Out, you need a payment of that size to reach Loop. If you don't have quality and enough outbound, then it would result in an off-chain failure.

**Comment by levmi** [comment]
Sounds good, thanks for the heads up. Also, if you're looking for a better experience with regard to status updates on Loops, you could try using https://terminal.lightning.engineering/ It's the latest and greatest UX flows for Loop and includes stuff like Automated fee management, personalized dashboard with accounting built in, etc. The LiT locally hosted UI you posted is now a bit dated, so that would probably improve your experience. 

Thanks again for the report and for following up!
