### ISSUE TITLE
Reuse existing lnd.conf file without modification

### ISSUE THREAD

**Issue by halseth** [lightninglabs/lightning-terminal#73]
This would allow easily checking out terminal without messing with the conf file, and easily go back to lnd proper when checking is done.

**Comment by guggero** [comment]
I've kind of addressed this issue in https://github.com/lightninglabs/lightning-terminal/pull/116.

Re-using the `lnd.conf` directly isn't really feasible because then you'd need more than one config file to add the options for `loop` and `faraday`.
What I ended up doing is giving LiT its own file by default (located in `~/.lit/lit.conf`) that can be created by copying `lnd.conf`, adding the `lnd.` prefixes and removing (or commenting out) all section headers (`[...]`).

That way you can try out LiT with minimal effort and without needing to change the original `lnd.conf`. Would that also work for you, @halseth ?

**Comment by halseth** [comment]
I was thinking just pointing Lit to the various conf files: `lit --lndconf=./lnd/lnd.conf --loopconf=./loop/loop.conf`.

Is that hard to achieve?

**Comment by halseth** [comment]
Original reason I created the issue was 
> This would allow easily checking out terminal without messing with the conf file, and easily go back to lnd proper when checking is done.

I think that is indeed addressed with #116 since we can just connect to the running setup 😄
