### ISSUE TITLE
Host for Syncing Universe State is down since a while now. (universe.lightning.finance)

### ISSUE THREAD

**Issue by GTCLive** [lightninglabs/lightning-terminal#895]
Periodically filling the logs with _failed to connect_. Not sure if that's a good thing, neither know what is this fed universe thing is, but thought of reporting this for it to be removed or amended with a functional host. 

# lnd.log
`2024-11-06 11:59:57.432 [INF] UNIV: Synchronizing with 1 federation members`
`2024-11-06 11:59:57.437 [INF] UNIV: Syncing Universe state with server=(universe.ServerAddr) {`
` ID: (int64) 1,`
` addrStr: (string) (len=32) "universe.lightning.finance:10029",`
` addr: (net.Addr) <nil>`
`}`

`2024-11-06 11:59:57.438 [INF] UNIV: Attempting to sync universe: host=universe.lightning.finance:10029, sync_type=full, ids=([]universe.Identifier) <nil>`

`2024-11-06 11:59:57.647 [INF] UNIV: Fetching 0 roots`
`2024-11-06 11:59:57.647 [INF] UNIV: Obtained 0 roots from remote Universe server`
`2024-11-06 11:59:57.648 [WRN] GRPC: [core] [Channel #155 SubChannel #156]grpc: addrConn.createTransport failed to connect to {Addr: "35.82.128.37:10029", ServerName: "35.82.128.37:10029", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 35.82.128.37:10029: operation was canceled"`

![Screenshot_2024-11-06_12-09-03](https://github.com/user-attachments/assets/01b1db2e-4c8d-4993-905f-b984d3b0dae9)

**Comment by dstadulis** [comment]
Hmm unable to reproduce:
```shell
$ nc -zv universe.lightning.finance 10029
Connection to universe.lightning.finance port 10029 [tcp/*] succeeded!
$ nc -zv 35.82.128.37 10029
Connection to 35.82.128.37 port 10029 [tcp/*] succeeded!
```

**Comment by GTCLive** [comment]
Mind sharing your dns provider so we can hook up to them? Prolly easier that way...

![Screenshot_2024-11-06_18-18-34](https://github.com/user-attachments/assets/890ea164-bd6a-4ebe-abe5-fb9281953b05)

**Comment by guggero** [comment]
I don't think it's a DNS issue, as we seem to get the same IP address. I think the confusion comes from the server not answering to `ping`, which is just a firewall configuration.
The fact that you get a successful response from `nc` seems to confirm that.

I think it's just some GRPC internal mechanism, since the actual error message seems to be `Error while dialing: dial tcp 35.82.128.37:10029: operation was canceled"`. So an attempt was canceled (perhaps because another attempt is being made).

You can safely turn off those logs by setting `--lnd.debuglevel=info,GRPC=off` (or `--remote.lit-debuglevel=info,GRPC=off` depending on the way you run `litd`.

If you aren't using taproot assets at all, you can also turn off the integrated daemon with `--taproot-assets-mode=disable`.

I'm also going to turn the `GRPC` log level off by default, as it causes more confusion that it is helpful.

**Comment by GTCLive** [comment]
Awesome, thanks. Meanwhile I am still unable to have a connection to universe.lightning.finance:10029 from within integrated litd (lnd).  Same `Transport failed to connect` error. 

The log=off silencing and taproot shutting down params worked perfectly fine though. Thanks for those hints!
